server:
  port: 8004
spring:
  application:
    name: menu-oss
  servlet:
    multipart:
      max-request-size: 15MB  # 最大支持请求大小
      enabled: true           #默认支持文件上传
      max-file-size: 10MB     #默认支持文件上传
aliyun:
  oss:
    file:
      endpoint: xxxxx
      keyid: xxxxx
      keysecret: xxxx
      bucketname:

